apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
  namespace: deploya-system
spec:
  selector:
    matchLabels:
      app: flask-hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
      - name: flask-hello-world
        image: IMAGE
        ports:
        - containerPort: 80
